# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jutsu < Formula
  desc "Open skills for AI coding agents — install, list, and manage skills across Claude, Codex, and Gemini."
  homepage "https://kaijutsu.dev"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.14.0/jutsu_0.14.0_darwin_amd64.tar.gz"
      sha256 "15cca0d4b15a1bf4921a7a98cc43484d7623de04c88b2e2db576f04bc7ce8b19"

      define_method(:install) do
        bin.install "jutsu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.14.0/jutsu_0.14.0_darwin_arm64.tar.gz"
      sha256 "10ab6232e86c77ec96e17ba86170b0237f06ec769c75b837994e4f2ef0b86622"

      define_method(:install) do
        bin.install "jutsu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.14.0/jutsu_0.14.0_linux_amd64.tar.gz"
      sha256 "af2c380f9b3c99fa044b2400bfae19e15e42ec4074f017332e2843de1880bc44"
      define_method(:install) do
        bin.install "jutsu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.14.0/jutsu_0.14.0_linux_arm64.tar.gz"
      sha256 "6e268472e1013c70426c76450fd8e11e930a3d71d2dfac8647f38ee8e36d147a"
      define_method(:install) do
        bin.install "jutsu"
      end
    end
  end

  test do
    system "#{bin}/jutsu --version"
  end
end
