# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jutsu < Formula
  desc "Open skills for AI coding agents — install, list, and manage skills across Claude, Codex, and Gemini."
  homepage "https://kaijutsu.dev"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.9.0/jutsu_0.9.0_darwin_amd64.tar.gz"
      sha256 "1cded710edb9a257096839648f59f73fb7a87fe3d5e477310cea7bceb62aceae"

      define_method(:install) do
        bin.install "jutsu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.9.0/jutsu_0.9.0_darwin_arm64.tar.gz"
      sha256 "97b0a705b5b7c5e963b0f94e28ab1a5acae47c3636dd41d5b48f8eee851f2f87"

      define_method(:install) do
        bin.install "jutsu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.9.0/jutsu_0.9.0_linux_amd64.tar.gz"
      sha256 "58e6b1c90659d50418d4136415a58397a82ccc7e03cb79e52cd3031d25502e20"
      define_method(:install) do
        bin.install "jutsu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/momentmaker/kaijutsu/releases/download/v0.9.0/jutsu_0.9.0_linux_arm64.tar.gz"
      sha256 "37008ad4b174e6d9045a16c4e35107ed01225c697c1ee3fd47d099e5bcd88d62"
      define_method(:install) do
        bin.install "jutsu"
      end
    end
  end

  test do
    system "#{bin}/jutsu --version"
  end
end
